name: Test, Build and Release apk

on:
  push:
    tags:
      - "*"

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.0.0"

      - run: flutter pub get

      - run: flutter build apk --release

      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.RELEASE_TOKEN }}
